bankingapp:
  db:
    url: jdbc:h2:mem:bankdb;MODE=MySql
    username: bank
    password: bank
#  liquibase:
#    contexts: local
#  h2.console: true

springdoc:
  show-login-endpoint: true
  enable-spring-security: true
  show-oauth2-endpoints: true
  swagger-ui.csrf.enabled: true